### PR TITLE
Add read_class method

### LINKED ISSUE #2: Labels are currently hard coded
in dataset.py, need a read_classes() method take in a dict of classes either from file or as an arg. Everything is just hard coded as tree.

### PR DESCRIPTION
**Pull request by dwaipayan05**
Might Fix #2

### CODE REVIEW

**Comment by henrykironde** [comment]
Could you install yapf `pip install yapf`
 And refactor the code using this command
`yapf -d --recursive deepforest/ --style=.style.yapf`

**Comment by dwaipayan05** [comment]
Yes
I did that. Should I push the refactored code ? Or paste them here.

**Comment by bw4sz** [comment]
Thanks for your first PR. Our general philosophy is that all new functions must have an accompanying unit test. I can help if this isn't something you are comfortable with. Imagine that we want to prove that your new function works. Not that it 'might' fix it. To do that we would want a test that asserts it can read a new classes file, make a prediction and those predictions are the same as the expected classes and not 'Tree'. There are some other details, but let's start there.

In https://github.com/weecology/DeepForest-pytorch/blob/master/tests/test_dataset.py

there would be a test something like following

```
def test_mutlfile():
    csv_file = get_data("testfile_multi.csv")
    root_dir = os.path.dirname(csv_file)
    ds = dataset.TreeDataset(csv_file=csv_file,
                             root_dir=root_dir,
                             transforms=None)
    raw_data = pd.read_csv(csv_file)
    
    assert len(ds) == len(raw_data.image_path.unique())
    
    for i in range(len(ds)):
        #Between 0 and 1
        path, image, targets = ds[i]
        assert image.max() <= 1
        assert image.min() >= 0
        assert targets["boxes"].shape == (79, 4)
        assert targets["labels"].shape == (79,)
        
        #The number of labels needs to be equal to the labels in the dataset
        len(np.unique(targets["labels"])) == len(raw_data.label.unique())
```

We would then need a prediction test in test_main.

**Comment by bw4sz** [comment]
Also note the test failures for existing tests introduced by this PR. See above.

**Comment by dwaipayan05** [comment]
Okay. I will look into it. I have not done unit testing per se. But, happy to learn !

**Comment by henrykironde** [comment]
@dwaipayan05, yes push the refactored code please.

**Comment by bw4sz** [comment]
closing, superseded by commit 484ad98c00a92032d16b69483b232018587689d9

**Pull request closed without merging**
