### PR TITLE
add soft nms method for predict tile function

### PR DESCRIPTION
**Pull request by dingyif**
#5  Add the corresponding test cases to make sure it works.

### CODE REVIEW

**Comment by bw4sz** [comment]
Thanks. Let's change the arg

```
method=1 
```
 
to 
```
soft_nms = False
```
Better coding pattern so that you don't need to look up docs. default, soft_nms=False

**Comment by dingyif** [comment]
Thanks for the comment, working on it.

**Comment by bw4sz** [comment]
Thanks. closes #5

**Comment by dingyif** [comment]
I think my IDE added `from deepforest.utilities import soft_nms` this in the `test_main.py`, which is unnecessary. 
Sorry for the mistake.

**Pull request merged**
